<?php
/**
 * *© Copyright 2018 - 2020 Visa. All Rights Reserved.**
 *
 * NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.*
 *
 *  By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy (developer.visa.com/privacy).In addition, all permissible uses of the Software must be in support of Visa products, programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com). **THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL FAULTS” BASIS WITHOUT WARRANTY OR  CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.** All brand names are the property of their respective owners, used for identification purposes only, and do not imply product endorsement or affiliation with Visa. Any links to third party sites are for your information only and equally  do not constitute a Visa endorsement. Visa has no insight into and control over third party content and code and disclaims all liability for any such components, including continued availability and functionality. Benefits depend on implementation details and business factors and coding steps shown are exemplary only and do not reflect all necessary elements for the described capabilities. Capabilities and features are subject to Visa’s terms and conditions and may require development,implementation and resources by you based on your business and operational details. Please refer to the specific API documentation for details on the requirements, eligibility and geographic availability.*
 *
 * This Software includes programs, concepts and details under continuing development by Visa. Any Visa features,functionality, implementation, branding, and schedules may be amended, updated or canceled at Visa’s discretion.The timing of widespread availability of programs and functionality is also subject to a number of factors outside Visa’s control,including but not limited to deployment of necessary infrastructure by issuers, acquirers, merchants and mobile device manufacturers.*
 *
 */
/**
 * Funds_transferApiTest
 *
 * @category Class
 * @package  funds_transfer_api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Funds Transfer API
 *
 * The Funds Transfer API can pull funds from the sender&apos;s Visa account (in preparation for pushing funds to a recipient&apos;s account) in an Account Funding Transaction (AFT).  Additionally, the Funds Transfer API also provides functionality to push funds to the recipient&apos;s Visa account in an Original Credit Transaction (OCT).  If a transaction is declined, the Funds Transfer API can also return the funds to the sender&apos;s funding source in an Account Funding Transaction Reversal (AFTR). The API has been enhanced to allow originators to send their PushFundsTransactions(OCTs) and PullFundsTransactions(AFTs) to Visa for routing to multiple U.S. debit networks.
 *
 * OpenAPI spec version: v1
 * Contact:
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace funds_transfer_api\apitest;

require_once(__DIR__ . '/../../globalConfig.php');
require_once(__DIR__ . '/../../src/Configuration.php');
require_once(__DIR__ . '/../../src/ObjectSerializer.php');
require_once(__DIR__ . '/../../src/ApiException.php');
require_once(__DIR__ . '/../../src/ApiClient.php');

require_once(__DIR__ . '/../../src/model/Address.php');
require_once(__DIR__ . '/../../src/model/AddressVerificationData.php');
require_once(__DIR__ . '/../../src/model/CardAcceptor.php');
require_once(__DIR__ . '/../../src/model/MagneticStripeData.php');
require_once(__DIR__ . '/../../src/model/MerchantVerificationValue.php');
require_once(__DIR__ . '/../../src/model/MultipullfundspostPayload.php');
require_once(__DIR__ . '/../../src/model/MultipullfundspostResponse.php');
require_once(__DIR__ . '/../../src/model/MultipullfundstransactionsgetResponse.php');
require_once(__DIR__ . '/../../src/model/MultipushfundspostPayload.php');
require_once(__DIR__ . '/../../src/model/MultipushfundspostResponse.php');
require_once(__DIR__ . '/../../src/model/MultipushfundstransactionsgetResponse.php');
require_once(__DIR__ . '/../../src/model/MultireversefundspostPayload.php');
require_once(__DIR__ . '/../../src/model/MultireversefundspostResponse.php');
require_once(__DIR__ . '/../../src/model/MultireversefundstransactionsgetResponse.php');
require_once(__DIR__ . '/../../src/model/OriginalDataElements.php');
require_once(__DIR__ . '/../../src/model/PinData.php');
require_once(__DIR__ . '/../../src/model/PointOfServiceCapability.php');
require_once(__DIR__ . '/../../src/model/PointOfServiceData.php');
require_once(__DIR__ . '/../../src/model/PullfundspostPayload.php');
require_once(__DIR__ . '/../../src/model/PullfundspostResponse.php');
require_once(__DIR__ . '/../../src/model/PullfundstransactionsgetResponse.php');
require_once(__DIR__ . '/../../src/model/PushfundspostPayload.php');
require_once(__DIR__ . '/../../src/model/PushfundspostResponse.php');
require_once(__DIR__ . '/../../src/model/PushfundstransactionsgetResponse.php');
require_once(__DIR__ . '/../../src/model/ReversefundspostPayload.php');
require_once(__DIR__ . '/../../src/model/ReversefundspostResponse.php');
require_once(__DIR__ . '/../../src/model/ReversefundstransactionsgetResponse.php');
require_once(__DIR__ . '/../../src/model/SecurityRelatedControlInfo.php');

require_once(__DIR__ . '/../../src/api/Funds_transferApi.php');

use funds_transfer_api\api\Funds_transferApi;
use funds_transfer_api\Configuration;
use globalConfig\GlobalConfig;

/**
 * Funds_transferApiTest Class Doc Comment
 *
 * @category Class
 * @package  funds_transfer_api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Funds_transferApiTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
        $gc = new GlobalConfig();
        $config = Configuration::getDefaultConfiguration();

        // Configure HTTP basic authorization
        $config->setUsername($gc->getUserName());
        $config->setPassword($gc->getPassword());
        $config->setCertificatePath($gc->getCertificatePath());
        $config->setPrivateKey($gc->getPrivateKeyPath());
        $config->setCaCertPath($gc->getCaCertPath());

        // Configure API key authorization:
        $config->setSharedSecret($gc->getSharedSecret());
        $config->setApiKey("apikey", $gc->getApiKey());

        // Configure proxy settings
        $config->setCurlProxyHost($gc->getProxyHost());
        $config->setCurlProxyPort($gc->getProxyPort());
        $config->setCurlProxyUser($gc->getProxyUser());
        $config->setCurlProxyPassword($gc->getProxyPassword());

        echo '\n.................Testing Funds_transferApi...........................\n';
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Test case for getmultipullfundstransactions
     *
     * .
     *
     */
    public function testGetmultipullfundstransactions()
    {
        echo "\nMaking a call to Getmultipullfundstransactions()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Getmultipullfundstransactions($this->addRandom('random'));

        $this->assertNotNull($result);

    }

    public function addRandom($oldPayload)
    {
        $pattern = '/random/i';
        $replacement = $this->generateRandomString(5);
        $oldPayload = preg_replace($pattern, $replacement, $oldPayload);

        $pattern = '/random_integer/i';
        return preg_replace($pattern, '1', $oldPayload);
    }

    function generateRandomString($length = 10)
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $randomString = substr(str_shuffle($characters), 0, $length);
        return $randomString;
    }

    /**
     * Test case for getmultipushfundstransactions
     *
     * .
     *
     */
    public function testGetmultipushfundstransactions()
    {
        echo "\nMaking a call to Getmultipushfundstransactions()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Getmultipushfundstransactions($this->addRandom('random'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for getmultireversefundstransactions
     *
     * .
     *
     */
    public function testGetmultireversefundstransactions()
    {
        echo "\nMaking a call to Getmultireversefundstransactions()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Getmultireversefundstransactions($this->addRandom('random'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for getpullfundstransactions
     *
     * .
     *
     */
    public function testGetpullfundstransactions()
    {
        echo "\nMaking a call to Getpullfundstransactions()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Getpullfundstransactions($this->addRandom('random'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for getpushfundstransactions
     *
     * .
     *
     */
    public function testGetpushfundstransactions()
    {
        echo "\nMaking a call to Getpushfundstransactions()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Getpushfundstransactions($this->addRandom('random'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for getreversefundstransactions
     *
     * .
     *
     */
    public function testGetreversefundstransactions()
    {
        echo "\nMaking a call to Getreversefundstransactions()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Getreversefundstransactions($this->addRandom('random'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for postmultipullfunds
     *
     * .
     *
     */
    public function testPostmultipullfunds()
    {
        echo "\nMaking a call to Postmultipullfunds()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Postmultipullfunds($this->addRandom('random'), $this->transformPayload('{"localTransactionDateTime":"2016-11-17T00:24:00","businessApplicationId":"AA","merchantCategoryCode":"6012","acquirerCountryCode":"608","request":[{"localTransactionDateTime":"2016-11-17T00:24:00","senderCardExpiryDate":"2020-12","amount":"100.00","retrievalReferenceNumber":"401010101011","cardAcceptor":{"idCode":"5678","address":{"county":"00","country":"USA","state":"CA","zipCode":"94454"},"terminalId":"1234","name":"Mr Smith"},"systemsTraceAuditNumber":"101011","senderCurrencyCode":"USD","cavv":"0700020718799100000002980179911000000000","senderPrimaryAccountNumber":"4895140000066666"},{"localTransactionDateTime":"2016-11-17T00:24:00","senderCardExpiryDate":"2020-12","amount":"100.00","retrievalReferenceNumber":"401010101011","cardAcceptor":{"idCode":"5678","address":{"county":"00","country":"USA","state":"CA","zipCode":"94454"},"terminalId":"1234","name":"Mr Smith"},"systemsTraceAuditNumber":"101011","senderCurrencyCode":"USD","cavv":"0700020718799100000002980179911000000000","senderPrimaryAccountNumber":"4895140000066666"}],"acquiringBin":"408999"}'));

        $this->assertNotNull($result);

    }

    public function transformPayload($oldPayload)
    {
        $payload = $this->editLocalTime($oldPayload);
        $payload = $this->addRandom($payload);
        $payload = json_decode($payload, true);
        return $payload;
    }

    public function editLocalTime($oldPayload)
    {

        date_default_timezone_set("America/Los_Angeles");
        $timestamp = date("Y-m-d\TH:i:s");
        $pattern = '/"localTransactionDateTime":".{19}"/i';
        $replacement = '"localTransactionDateTime": "' . $timestamp . '"';
        $oldPayload = preg_replace($pattern, $replacement, $oldPayload);

        $timestamp = date("mdHis");
        $pattern = '/"dateTimeLocal":".{10}"/i';
        $replacement = '"dateTimeLocal": "' . $timestamp . '"';
        return preg_replace($pattern, $replacement, $oldPayload);

    }

    /**
     * Test case for postmultipushfunds
     *
     * .
     *
     */
    public function testPostmultipushfunds()
    {
        echo "\nMaking a call to Postmultipushfunds()\n";

        $timestamp = date("Y-m-d\TH:i:s");

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Postmultipushfunds($this->addRandom('random'), $this->transformPayload('{"localTransactionDateTime":"' . $timestamp . '","businessApplicationId":"AA","merchantCategoryCode":"6012","acquirerCountryCode":"840","request":[{"senderCity":"My City","senderAccountNumber":"4005520000011126","senderStateCode":"CA","feeProgramIndicator":"123","localTransactionDateTime":"2016-11-17T18:24:24","recipientPrimaryAccountNumber":"4957030420210454","transactionCurrencyCode":"USD","transactionIdentifier":"234234234234234","sourceOfFundsCode":"01","senderReference":"","senderAddress":"My Address","retrievalReferenceNumber":"401010101011","systemsTraceAuditNumber":"101011","senderCountryCode":"USA","cardAcceptor":{"idCode":"5678","address":{"county":"00","country":"USA","state":"CA","zipCode":"94454"},"terminalId":"1234","name":"Mr Smith"},"recipientName":"Akhila","amount":"100.00","senderName":"Mr Name"},{"senderCity":"My City","senderAccountNumber":"4840920103511221","senderStateCode":"CA","feeProgramIndicator":"123","localTransactionDateTime":"2016-11-17T18:24:24","recipientPrimaryAccountNumber":"4957030420210454","transactionCurrencyCode":"USD","transactionIdentifier":"234234234234234","sourceOfFundsCode":"01","senderReference":"","senderAddress":"My Address","retrievalReferenceNumber":"401010101012","systemsTraceAuditNumber":"101012","senderCountryCode":"USA","cardAcceptor":{"idCode":"5678","address":{"county":"00","country":"USA","state":"CA","zipCode":"94454"},"terminalId":"1234","name":"Mr Smith"},"recipientName":"Akhila","amount":"100.00","senderName":"Mr Name"}],"acquiringBin":"408999"}'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for postmultireversefunds
     *
     * .
     *
     */
    public function testPostmultireversefunds()
    {
        echo "\nMaking a call to Postmultireversefunds()\n";

        $timestamp = date("Y-m-d\TH:i:s");

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Postmultireversefunds($this->transformPayload('{"localTransactionDateTime":"' . $timestamp . '","acquiringBin":"408999","businessApplicationId":"AA","acquirerCountryCode":"840","request":[{"localTransactionDateTime":"2016-11-17T19:24:44","senderCardExpiryDate":"2020-12","transactionIdentifier":"101010101010","retrievalReferenceNumber":"401010101011","cardAcceptor":{"idCode":"5678","address":{"county":"00","country":"USA","state":"CA","zipCode":"94454"},"terminalId":"1234","name":"Mr Smith"},"originalDataElements":{"acquiringBin":"408999","systemsTraceAuditNumber":"228112","approvalCode":"1ABCDE","transmissionDateTime":"2016-11-17T19:24:44"},"systemsTraceAuditNumber":"101011","senderCurrencyCode":"USD","amount":"100.00","senderPrimaryAccountNumber":"4485810000000131"},{"localTransactionDateTime":"2016-11-17T19:24:44","senderCardExpiryDate":"2020-12","transactionIdentifier":"101010101010","retrievalReferenceNumber":"401010101011","cardAcceptor":{"idCode":"5678","address":{"county":"00","country":"USA","state":"CA","zipCode":"94454"},"terminalId":"1234","name":"Mr Smith"},"originalDataElements":{"acquiringBin":"408999","systemsTraceAuditNumber":"228112","approvalCode":"1ABCDE","transmissionDateTime":"2016-11-17T19:24:44"},"systemsTraceAuditNumber":"101011","senderCurrencyCode":"USD","amount":"100.00","senderPrimaryAccountNumber":"4485810000000131"}]}'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for postpullfunds
     *
     * .
     *
     */
    public function testPostpullfunds()
    {
        echo "\nMaking a call to Postpullfunds()\n";

        $timestamp = date("Y-m-d\TH:i:s");

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Postpullfunds($this->transformPayload("{\"localTransactionDateTime\": \"" . $timestamp . "\", \"businessApplicationId\": \"AA\", \"cpsAuthorizationCharacteristicsIndicator\": \"Y\", \"senderCardExpiryDate\": \"2015-10\", \"amount\": \"124.02\", \"acquirerCountryCode\": \"840\", \"retrievalReferenceNumber\": \"330000550000\", \"cardAcceptor\": {\"idCode\": \"ABCD1234ABCD123\", \"address\": {\"county\": \"081\", \"country\": \"USA\", \"state\": \"CA\", \"zipCode\": \"94404\"}, \"terminalId\": \"ABCD1234\", \"name\": \"Visa Inc. USA-Foster City\"}, \"acquiringBin\": \"408999\", \"systemsTraceAuditNumber\": \"451001\", \"nationalReimbursementFee\": \"11.22\", \"senderCurrencyCode\": \"USD\", \"cavv\": \"0700100038238906000013405823891061668252\", \"foreignExchangeFeeTransaction\": \"11.99\", \"addressVerificationData\": {\"postalCode\": \"12345\", \"street\": \"XYZ St\"}, \"senderPrimaryAccountNumber\": \"4895142232120006\", \"surcharge\": \"11.99\"}"));

        $this->assertNotNull($result);

    }

    /**
     * Test case for postpushfunds
     *
     * .
     *
     */
    public function testPostpushfunds()
    {
        echo "\nMaking a call to Postpushfunds()\n";

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Postpushfunds($this->transformPayload('{"businessApplicationId":"AA","transactionIdentifier":"381228649430015","cardAcceptor":{"idCode":"CA-IDCode-77765","address":{"county":"San Mateo","country":"USA","state":"CA","zipCode":"94404"},"terminalId":"TID-9999","name":"Visa Inc. USA-Foster City"},"senderAddress":"901 Metro Center Blvd","sourceOfFundsCode":"05","recipientName":"rohan","senderName":"Mohammed Qasim","senderStateCode":"CA","merchantCategoryCode":"6012","acquirerCountryCode":"840","senderReference":"","recipientPrimaryAccountNumber":"4957030420210496","retrievalReferenceNumber":"412770451018","senderAccountNumber":"4653459515756154","transactionCurrencyCode":"USD","acquiringBin":"408999","pointOfServiceData":{"posConditionCode":"00","panEntryMode":"90","motoECIIndicator":"0"},"senderCity":"Foster City","localTransactionDateTime":"2016-11-17T00:39:13","amount":"124.05","systemsTraceAuditNumber":"451018","senderCountryCode":"124"}'));

        $this->assertNotNull($result);

    }

    /**
     * Test case for postreversefunds
     *
     * .
     *
     */
    public function testPostreversefunds()
    {
        echo "\nMaking a call to Postreversefunds()\n";

        $timestamp = date("Y-m-d\TH:i:s");

        $api_instance = new Funds_transferApi;
        $result = $api_instance->Postreversefunds($this->transformPayload('{"localTransactionDateTime":"' . $timestamp . '","businessApplicationId":"AA","senderCardExpiryDate":"2015-10","transactionIdentifier":"381228649430011","acquirerCountryCode":"608","retrievalReferenceNumber":"330000550000","cardAcceptor":{"idCode":"VMT200911026070","address":{"county":"San Mateo","country":"USA","state":"CA","zipCode":"94404"},"terminalId":"365539","name":"Visa Inc. USA-Foster City"},"originalDataElements":{"acquiringBin":"408999","systemsTraceAuditNumber":"897825","approvalCode":"20304B","transmissionDateTime":"2016-11-17T19:04:06"},"acquiringBin":"408999","systemsTraceAuditNumber":"451050","senderCurrencyCode":"USD","pointOfServiceCapability":{"posTerminalType":"4","posTerminalEntryCapability":"2"},"amount":"24.01","pointOfServiceData":{"posConditionCode":"00","panEntryMode":"90","motoECIIndicator":"0"},"senderPrimaryAccountNumber":"4895100000055127"}'));

        $this->assertNotNull($result);

    }

}