<?php
/**
 * *© Copyright 2018 - 2020 Visa. All Rights Reserved.**
 *
 * NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.*
 *
 *  By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy (developer.visa.com/privacy).In addition, all permissible uses of the Software must be in support of Visa products, programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com). **THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL FAULTS” BASIS WITHOUT WARRANTY OR  CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.** All brand names are the property of their respective owners, used for identification purposes only, and do not imply product endorsement or affiliation with Visa. Any links to third party sites are for your information only and equally  do not constitute a Visa endorsement. Visa has no insight into and control over third party content and code and disclaims all liability for any such components, including continued availability and functionality. Benefits depend on implementation details and business factors and coding steps shown are exemplary only and do not reflect all necessary elements for the described capabilities. Capabilities and features are subject to Visa’s terms and conditions and may require development,implementation and resources by you based on your business and operational details. Please refer to the specific API documentation for details on the requirements, eligibility and geographic availability.*
 *
 * This Software includes programs, concepts and details under continuing development by Visa. Any Visa features,functionality, implementation, branding, and schedules may be amended, updated or canceled at Visa’s discretion.The timing of widespread availability of programs and functionality is also subject to a number of factors outside Visa’s control,including but not limited to deployment of necessary infrastructure by issuers, acquirers, merchants and mobile device manufacturers.*
 *
 */
/**
 * PointOfServiceData
 *
 * @category Class
 * @package  funds_transfer_api
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Funds Transfer API
 *
 * The Funds Transfer API can pull funds from the sender&apos;s Visa account (in preparation for pushing funds to a recipient&apos;s account) in an Account Funding Transaction (AFT).  Additionally, the Funds Transfer API also provides functionality to push funds to the recipient&apos;s Visa account in an Original Credit Transaction (OCT).  If a transaction is declined, the Funds Transfer API can also return the funds to the sender&apos;s funding source in an Account Funding Transaction Reversal (AFTR). The API has been enhanced to allow originators to send their PushFundsTransactions(OCTs) and PullFundsTransactions(AFTs) to Visa for routing to multiple U.S. debit networks.
 *
 * OpenAPI spec version: v1
 * Contact:
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace App\Visa\model;

use ArrayAccess;

/**
 * PointOfServiceData Class Doc Comment
 *
 * @category    Class
 * @description &lt;b&gt;Note:&lt;/b&gt; For a CardPresent Transactions, this field is required.
 * @package     funds_transfer_api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PointOfServiceData implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     * @var string
     */
    protected static $swaggerModelName = 'pointOfServiceData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerTypes = [
        'pos_condition_code' => 'int',
        'pan_entry_mode' => 'int',
        'moto_eci_indicator' => 'string'
    ];
    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'pos_condition_code' => 'posConditionCode',
        'pan_entry_mode' => 'panEntryMode',
        'moto_eci_indicator' => 'motoECIIndicator'
    ];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'pos_condition_code' => 'setPosConditionCode',
        'pan_entry_mode' => 'setPanEntryMode',
        'moto_eci_indicator' => 'setMotoEciIndicator'
    ];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'pos_condition_code' => 'getPosConditionCode',
        'pan_entry_mode' => 'getPanEntryMode',
        'moto_eci_indicator' => 'getMotoEciIndicator'
    ];
    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['pos_condition_code'] = isset($data['pos_condition_code']) ? $data['pos_condition_code'] : null;
        $this->container['pan_entry_mode'] = isset($data['pan_entry_mode']) ? $data['pan_entry_mode'] : null;
        $this->container['moto_eci_indicator'] = isset($data['moto_eci_indicator']) ? $data['moto_eci_indicator'] : null;
    }

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets pos_condition_code
     * @return int
     */
    public function getPosConditionCode()
    {
        return $this->container['pos_condition_code'];
    }

    /**
     * Sets pos_condition_code
     * @param int $pos_condition_code <b>Note:</b> For a CardPresent scenario, this field is required.
     * @return $this
     */
    public function setPosConditionCode($pos_condition_code)
    {
        $this->container['pos_condition_code'] = $pos_condition_code;

        return $this;
    }

    /**
     * Gets pan_entry_mode
     * @return int
     */
    public function getPanEntryMode()
    {
        return $this->container['pan_entry_mode'];
    }

    /**
     * Sets pan_entry_mode
     * @param int $pan_entry_mode <b>Note:</b> For a CardPresent scenario, this field is required.
     * @return $this
     */
    public function setPanEntryMode($pan_entry_mode)
    {
        $this->container['pan_entry_mode'] = $pan_entry_mode;

        return $this;
    }

    /**
     * Gets moto_eci_indicator
     * @return string
     */
    public function getMotoEciIndicator()
    {
        return $this->container['moto_eci_indicator'];
    }

    /**
     * Sets moto_eci_indicator
     * @param string $moto_eci_indicator <b>Note:</b> If posConditionCode is 59, motoECIIndicator must be between 5-8. Default is set to 5 if not provided. If posConditionCode is 0, motoECIIndicator will not be sent. If cavv is not provided, then motoECIIndicator should be set as 7.
     * @return $this
     */
    public function setMotoEciIndicator($moto_eci_indicator)
    {
        $this->container['moto_eci_indicator'] = $moto_eci_indicator;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     * @param integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param integer $offset Offset
     * @param mixed $value Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\funds_transfer_api\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\funds_transfer_api\ObjectSerializer::sanitizeForSerialization($this));
    }
}
